# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en
title: KOFC7186
tagline: Strengthen Catholic Faith
email: feedback@kofc7186.org
description: >- # this means to ignore newlines until "baseurl:"
  Knights of Columbus, Council 7186, est 2005
  St Mary Magdalene, Apex, NC
baseurl: "/"
url: "https://kofc7186.github.io"
twitter_username: username
github_username: kofc7186
minimal_mistakes_skin: default
search: true
permalink: pretty
favicon: /assets/images/favicon-KOFC7186.ico
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
theme_color: '#ff8c66'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

# Build settings
markdown: kramdown
remote_theme: kofc7186/bulma-clean-theme
# Outputting
paginate: 5 # amount of posts to show
paginate_path: "/blog/page:num"

include:
  - _pages
  - _includes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

author:
  name   : "Council 7186 Apex NC"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "GK 7186"
      layout: post
      image: https://via.placeholder.com/1200x800
      hero_image: /assets/images/favicon-KOFC7186.ico
      show_sidebar: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# Site Settings

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
