version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3
    command: jekyll serve --watch --force_polling --verbose  --livereload
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll

